spring:
  profiles:
    active: dev
  application:
    name: demo
  ai:
    openai:
      temperature: 0.3
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
security:
  jwtSecret: C1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4Y5z6A7B8C9D0E1F2G3H4I5J6K7L8567B19546HJT0348g
  jwtExpirationMs: 604800000

---

spring:
  config:
    activate:
      on-profile: dev
  ai:
    vectorstore:
      redis:
        host: localhost
        port: 6379
        database: 0
        index: faqs
        prefix: "faq:"
        initialize-schema: true
  datasource:
    url: jdbc:mysql://localhost:3306/playbook
    username: root
    password: password


---

spring:
  config:
    activate:
      on-profile: prod
  ai:
    vectorstore:
      redis:
        host: orion-prod-redis-001.lyupna.0001.aps1.cache.amazonaws.com
        port: 6379
        database: 0
        index: faqs
        prefix: "faq:"
        initialize-schema: true
  datasource:
    url: jdbc:mysql://orion-prod.cyaervvtanuk.ap-south-1.rds.amazonaws.com/playbook
    username: playbookadmin
    password: ${DB_PASSWORD}